default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: label_maker_development
test:
  <<: *default
  database: label_maker_test
production:
  <<: *default
  database: label_maker_production
